modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/LordFokas/Cartography/issues" #optional

[[mods]] #mandatory
modId="cartography" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Cartography" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/cartography" #optional
updateJSONURL="https://raw.githubusercontent.com/LordFokas/ModVersions/master/Cartography.json" #optional
logoFile="cartography.png" #optional
# credits="" #optional
authors="LordFokas" #optional
description='''
Better mapping for TFC using Blaze Map
'''

# TerraFirmaCraft
[[dependencies.cartography]]
    modId="tfc"
    mandatory=true
    versionRange="[3.2,4)"
    ordering="NONE"
    side="BOTH"

# Blaze Map
[[dependencies.cartography]]
    modId="blazemap"
    mandatory=true
    versionRange="[0.7.0-dev,0.8)"
    ordering="NONE"
    side="BOTH"

# MinecraftForge
[[dependencies.cartography]]
    modId="forge"
    mandatory=true
    versionRange="[47.1,48)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.cartography]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.20.2)"
    ordering="NONE"
    side="BOTH"