modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="All rights reserved"
issueTrackerURL="https://github.com/LordFokas/Cartography/issues" #optional

[[mods]] #mandatory
modId="cartography" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Cartography" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/cartography" #optional
updateJSONURL="https://raw.githubusercontent.com/LordFokas/ModVersions/master/Cartography.json" #optional
logoFile="cartography.png" #optional
# credits="" #optional
authors="LordFokas" #optional
description='''
Better mapping for TFC using Blaze Map
'''

# TerraFirmaCraft
[[dependencies.cartography]]
    modId="tfc"
    mandatory=true
    versionRange="[2.2,)"
    ordering="NONE"
    side="BOTH"

# Blaze Map
[[dependencies.cartography]]
    modId="blazemap"
    mandatory=true
    versionRange="[0.5.16-beta,0.6)"
    ordering="NONE"
    side="BOTH"

# MinecraftForge
[[dependencies.cartography]]
    modId="forge"
    mandatory=true
    versionRange="[40.2,)"
    ordering="NONE"
    side="BOTH"

# Minecraft
[[dependencies.cartography]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"